version: "3.4"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    #container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    #volumes:
    #  - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: docker.io/bitnami/kafka:3.5
    #container_name: kafka
    ports:
      - "9092:9092"
    restart: unless-stopped
    #volumes:
    #  - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
      
  mongo:
    image: mongo:latest
    #container_name: mongo-container
    ports:
      - "27017:27017"
    restart: unless-stopped
    #volumes:
    #  - "mongodb_data_container:/data/db"
    
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    #container_name: sql-container
    restart: unless-stopped
    ports:
      - "1405:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd!"
      MSSQL_PID: "Express"
    #volumes:
    #  - "sqlserver_data:/var/opt/mssql"
    
  command-api:
    build:
      context: .
      dockerfile: Post.Cmd/Post.Cmd.Api/Dockerfile
    environment:
      - KAFKA_TOPIC=SocialMediaPostEvents
    ports:
      - "5010:80"
    restart: unless-stopped
    depends_on:
      - kafka
      - mongo
      - sql-server

  query-api:
    build:
      context: .
      dockerfile: Post.Query/Post.Query.Api/Dockerfile
    environment:
      - KAFKA_TOPIC=SocialMediaPostEvents
    ports:
      - "5011:80"
    restart: unless-stopped
    depends_on:
      - kafka
      - mongo
      - sql-server

  ocelot-gateway:
    build:
      context: .
      dockerfile: Gateway.Ocelot/Dockerfile
    ports:
      - "7006:80"
    restart: unless-stopped
    depends_on:
      - command-api
      - query-api
      
      
      
# volumes:
  # zookeeper_data:
    # driver: local
  # kafka_data:
    # driver: local
  # mongodb_data_container:
    # driver: local
  # sqlserver_data:
    # driver: local
    
   
networks:
  smPostNetwork:
    driver: bridge
    
