version: "3.4"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - smPostNetwork
      
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper
    networks:
      - smPostNetwork
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - smPostNetwork
    
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    ports:
      - "1405:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd!"
      MSSQL_PID: "Express"
    networks:
      - smPostNetwork
    
  command-api:
    build:
      context: .
      dockerfile: Post.Cmd/Post.Cmd.Api/Dockerfile
    environment:
      - KAFKA_TOPIC=SocialMediaPostEvents
    ports:
      - "5010:80"
    restart: unless-stopped
    depends_on:
      - kafka
      - mongo
      - sql-server
    networks:
      - smPostNetwork

  query-api:
    build:
      context: .
      dockerfile: Post.Query/Post.Query.Api/Dockerfile
    environment:
      - KAFKA_TOPIC=SocialMediaPostEvents
    ports:
      - "5011:80"
    restart: unless-stopped
    depends_on:
      - kafka
      - mongo
      - sql-server
    networks:
      - smPostNetwork

  ocelot-gateway:
    build:
      context: .
      dockerfile: Gateway.Ocelot/Dockerfile
    ports:
      - "7006:80"
    restart: unless-stopped
    depends_on:
      - command-api
      - query-api
    networks:
      - smPostNetwork
      
networks:
  smPostNetwork:
    driver: bridge
